### ISSUE TITLE
Unicode errors in name when logging in [fixed]

### ISSUE THREAD

**Issue by SweetShyGirl** [appu1232/Selfbot-for-Discord#2]
IDK what's these errors
```bash
Logged in as
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 29, in on_ready
    print(bot.user.name)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 148, in on_message
    if message.channel.id not in bot.self_log:
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute 'self_log'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 148, in on_message
    if message.channel.id not in bot.self_log:
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute 'self_log'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 148, in on_message
    if message.channel.id not in bot.self_log:
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute 'self_log'
```

**Comment by appu1232** [comment]
Hello,

Are you on Windows? Also, if you know, tell me what version of Python you
have installed.


On Mar 13, 2017 8:22 PM, "SweetShyGirl" <notifications@github.com> wrote:

IDK what's these errors

Logged in as
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py",
line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 29, in on_ready
    print(bot.user.name)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\encodings\cp437.py",
line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in
position 0-1: character maps to <undefined>Ignoring exception in
on_messageTraceback (most recent call last):  File
"C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py",
line 307, in _run_event    yield from getattr(self, event)(*args,
**kwargs)  File "appuselfbot.py", line 148, in on_message    if
message.channel.id not in bot.self_log:  File
"C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py",
line 296, in __getattr__    raise
AttributeError(msg.format(self.__class__, name))AttributeError:
'<class 'discord.ext.commands.bot.Bot'>' object has no attribute
'self_log'Ignoring exception in on_messageTraceback (most recent call
last):  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py",
line 307, in _run_event    yield from getattr(self, event)(*args,
**kwargs)  File "appuselfbot.py", line 148, in on_message    if
message.channel.id not in bot.self_log:  File
"C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py",
line 296, in __getattr__    raise
AttributeError(msg.format(self.__class__, name))AttributeError:
'<class 'discord.ext.commands.bot.Bot'>' object has no attribute
'self_log'Ignoring exception in on_messageTraceback (most recent call
last):  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py",
line 307, in _run_event    yield from getattr(self, event)(*args,
**kwargs)  File "appuselfbot.py", line 148, in on_message    if
message.channel.id not in bot.self_log:  File
"C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py",
line 296, in __getattr__    raise
AttributeError(msg.format(self.__class__, name))AttributeError:
'<class 'discord.ext.commands.bot.Bot'>' object has no attribute
'self_log'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/appu1232/Selfbot-for-Discord/issues/2>, or mute the
thread

**Comment by appu1232** [comment]
Ah, it seems to be a problem with your Discord username. My guess is you have some special characters in your username right? I've added a fix for it. Update the bot to the newest version and try running it again. Tell me if it works.

**Comment by SweetShyGirl** [comment]
@appu1232 Changed my name and it works, I'll upload the bot soon sorry for late reply because i just see this
New error
```bash
Ignoring exception in command server members
Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Kyle\vps\discord\Selfbot-for-Discord-master\cogs\misc.py", line 174, in members
    file.write(str(msg))
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60e' in position 1372: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 634, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 630, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60e' in position 1372: character maps to <undefined>
Ignoring exception in command stats
Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Kyle\vps\discord\Selfbot-for-Discord-master\cogs\misc.py", line 48, in stats
    em.add_field(name=u'\U0001F3AE Game', value=game)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\embeds.py", line 361, in add_field
    'value': str(value)
TypeError: __str__ returned non-string (type NoneType)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __str__ returned non-string (type NoneType)
```

**Comment by appu1232** [comment]
Yea this is pretty much the same problem where when you so >server members,
it comes across a name with special characters and it throws an error. I'll
fix it tomorrow.

**Comment by SweetShyGirl** [comment]
Is it possible to change embed color and auto embed all regular messages? @appu1232

**Comment by SweetShyGirl** [comment]
As far as I can see, there is no way to change the embed color from grey, no sort of embed settings either :(

**Comment by appu1232** [comment]
Depends on the embed but some are different colors. Custom Commands that are images have a purple color. Which embed are you looking to change the color of exactly?

As for auto embeding every comment, no I haven't made anything for that yet. For now, you'd just have to do >embed <whatever text>.

**Comment by SweetShyGirl** [comment]
@appu1232 I meant, you should allow us to change the color to whatever we prefer when using >embed <text>
The only color that it outputs is the normal ugly grey.

Also, you could add a feature to allow auto embedding of every messages sent by you (toggle on/off)

**Comment by SweetShyGirl** [comment]
If you do that I'll love the bot x10000

**Comment by appu1232** [comment]
I'll see what I can do. I've been planning on adding that anyway. It'll have to wait till at least the weekend or next week though, I'm a bit busy this week.

**Comment by SweetShyGirl** [comment]
@appu1232  Yes thanks a lot, where do I suggest features or report any other issue, just open a new issue?

**Comment by appu1232** [comment]
Hmm, yea I guess so.
