### ISSUE TITLE
Calc unable to calculate currencies

### ISSUE THREAD

**Issue by SweetShyGirl** [appu1232/Selfbot-for-Discord#3]
I could try to fix this myself, but i can't find the calc code
```bash
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 634, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnicodeEncodeError: 'charmap' codec can't encode character '\u2764' in position 8: character maps to <undefined>
Ignoring exception in command calc
Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Kyle\vps\discord\Selfbot-for-Discord-master\cogs\misc.py", line 375, in calc
    answer = str(eval(equation))
  File "<string>", line 1
    18,295,926,372,014,800/5000
                     ^
SyntaxError: invalid token

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: SyntaxError: invalid token (<string>, line 1)
Ignoring exception in command calc
Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Kyle\vps\discord\Selfbot-for-Discord-master\cogs\misc.py", line 375, in calc
    answer = str(eval(equation))
  File "<string>", line 1
    $18295926372014800/5000
    ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: SyntaxError: invalid syntax (<string>, line 1)
```

**Comment by SweetShyGirl** [comment]
Probably by stripping `,` and "$", but the output wouldn't be formatted :(

**Comment by appu1232** [comment]
Calculator is just meant for simple math calculations not conversions. Use the google command ``>g`` to get currency conversions with a google card. Ex: ``>g convert $500 to euros``

Also, give the message you inputted for these kinds of errors.

**Comment by SweetShyGirl** [comment]
Yea, i just asked a python support chat, i guess i would need to build my own currency calculator
I did 
>calc $number/number
And also 
>calc 123,456/123

They won't work
